spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cdx?useSSL=false&serverTimezone=UTC
#    url: jdbc:oracle:thin:@//192.168.1.100:1521/orcl
    username: root
    password: x5
server:
  port: 9011
mybatis:
  config-location: classpath:mybatis-config.xml